apiVersion: apps/v1
kind: Deployment
metadata:
  name: caf-frontend
  labels:
    app: caf-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caf-frontend
  template:
    metadata:
      labels:
        app: caf-frontend
    spec:
      containers:
        - name: caf-frontend
          imagePullPolicy: Always
          image: gcr.io/cards-against-friends-277922/caf-frontend:v1.0.0a
          ports:
            - containerPort: 80
              name: 80tcp300011
              protocol: TCP
